version: '3.8'
services:
  db:
    image: mysql:9.0
    restart: always
    environment:
      # Config from .env file
      - MYSQL_DATABASE={MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD={MYSQL_ROOT_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: